"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/watson.py']
APP_NAME = "Watson"
DATA_FILES = ['src/data.json', 'src/func.py']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'images/dock-icon.icns',
    'plist': {
        'LSUIElement': False,
    },
    'packages': ['rumps']
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
